version: "3"

services:
  server:
    build: server/
    command: python server.py
    volumes:
      - ./server:/server

  client1:
    build: client/
    # command: python client.py
    # Test
    command: tail -f /dev/null
    #command: python client.py
    volumes:
      - ./client:/client
    depends_on:
      - server
  client2:
    build: client/
    # command: python client.py
    # Test
    command: tail -f /dev/null
    #command: python client.py
    volumes:
      - ./client:/client
    depends_on:
      - server